### ISSUE TITLE
exposed credentials

### ISSUE THREAD

**Issue by michael-groble** [daneren2005/heroku-buildpack-twemproxy#1]
I'm looking to use tubepress/heroku-buildpack-twemproxy and caught the following line which looks like it originates in this repo.

https://github.com/daneren2005/heroku-buildpack-twemproxy/blob/master/bin/gen-twemproxy-conf.sh#L11

seems to be live.  you might want to change that.

**Comment by daneren2005** [comment]
I removed it and invalidated those redis credentials.  Thank you for letting me know about this.
